# site settings
title: Quien te financia
email: info@ciudadanointeligente.org
description: Descubre cómo se van a financiar los candidatos en las próximas elecciones en Chile.
baseurl: "http://quientefinancia.cl" # the subpath of your site, e.g. /blog/
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-41822715-1'
basedomain: quientefinancia.cl

# build settings
markdown: kramdown
